version: '3'
services:
  kwetter-service:
    restart: on-failure
    image: kwetter-service
    build: 
      context: ./
    ports:
      - "5000"
    networks:
      - kwetter
    env_file: ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kwetter-service
    ports:
      - "4000:4000"
    networks:
      - kwetter
networks:
  kwetter:
    driver: bridge

volumes: 
  db-config:
  db-data:
