version: '3'
services:
  kwetter-service:
    restart: on-failure
    image: kwetter-service
    build: 
      context: ./
    ports:
      - "5000"
    networks:
      - kwetter
    env_file: ./.env
    depends_on:
      - mongo
    expose:
      - "5000"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kwetter-service
    ports:
      - "4000:4000"
    networks:
      - kwetter
networks:
  kwetter:
    driver: bridge

volumes: 
  db-config:
  db-data:
