version: '3'
services:
  kwetter-service:
    restart: on-failure
    image: kwetter-service
    build: 
      context: ./
    ports:
      - "5000"
    env_file: ./.env
    deploy:
      replicas: 4

  nginx:
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kwetter-service
    ports:
      - "4000:4000"

volumes: 
  db-config:
  db-data:
